#+TITLE: macOS × Nix

+ [[https://developer.apple.com/macos/][macOS]] is good, but only the GUI-related parts.
+ [[https://nixos.org/download.html#download-nix][Nix]] and [[https://nixos.org/][NixOS]] are good, except for the GUI-related parts, such as X Window System, Wayland, etc.

Why not enjoy the best parts of them? Then, here *macOS × Nix* comes:
+ macOS provides great UI
+ Nix acts as a configuration and package manager, which makes macOS reproducible:
  + most parts of configurations are managed by Nix
  + all softwares are managed by Nix

* Choose macOS version
I'm using macOS Big Sur.

#+begin_quote
Following steps aren't tested on newer version of macOS.
#+end_quote

* Install macOS
First, [[https://support.apple.com/en-us/HT201372][create a bootable installer for macOS]].

Then, use the prepared USB flash drive to install macOS as normal.

Then, enable:
+ FileVault
+ Firewall

#+begin_note
APFS(encrypted) equals to APFS with File Vault enabled.
#+end_note

* setup macOS
** setup keyboard layout
If you are using non-standard keyboard layout, such as [[https://www.kaufmann.no/roland/dvorak/][Programmer Dovrak]], etc. It's time to set it up.

*** (optional) setup modifier keys
+ =Caps Lock= -> =Control=
+ =Option= -> =Command=
+ =Command= -> =Option=

*** (options) setup shortcuts for changing input sources
#+begin_src text
System Preferences > Keyboard > Shortcuts > Input Sources > Select input source
#+end_src

** (optional) setup global proxy
If you are in a country whose internet is audited by goverment. You'd better configure a proxy. Or, you will not be able to install Nix.

Possible tools:
+ [[https://nssurge.com/][Surge for Mac]]
+ [[https://github.com/yichengchen/clashX][ClashX]]
+ ...

* Install Nix
** download and verify installation script
From [[https://nixos.org/download.html#nix-verify-installation][official installation]]:
#+begin_src sh
$ curl -o install-nix-2.6.0 https://releases.nixos.org/nix/nix-2.6.0/install
$ curl -o install-nix-2.6.0.asc https://releases.nixos.org/nix/nix-2.6.0/install.asc
$ gpg2 --keyserver hkps://keyserver.ubuntu.com --recv-keys B541D55301270E0BCF15CA5D8170B4726D7198DE
$ gpg2 --verify ./install-nix-2.6.0.asc
#+end_src

If everything is fine, then install it via the recommended [[https://nixos.org/manual/nix/stable/installation/multi-user.html][multi-user installation]], and with macOS limited options:
#+begin_src sh
$ sh ./install-nix-2.6.0 --daemon --darwin-use-unencrypted-nix-store-volume
#+end_src

#+begin_quote
The option =--darwin-use-unencrypted-nix-store-volume= is no longer needed and will be removed in the future.
#+end_quote

** verify installation
#+begin_src sh
$ nix-env --version
#+end_src
