# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "is-docker-2.2.1" = {
      name = "is-docker";
      packageName = "is-docker";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-docker/-/is-docker-2.2.1.tgz";
        sha512 = "F+i2BKsFrH66iaUFc0woD8sLy8getkwTwtOBjvs56Cx4CgJDeKQeqfz8wAYiSb8JOprWhHH5p77PbmYCvvUuXQ==";
      };
    };
    "is-wsl-2.2.0" = {
      name = "is-wsl";
      packageName = "is-wsl";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-wsl/-/is-wsl-2.2.0.tgz";
        sha512 = "fKzAra0rGJUUBwGBgNkHZuToZcn+TtXHpeCgmkMJMMYx1sQDYaCSyjJBSCa2nH1DGm7s3n1oBnohoVTBaN7Lww==";
      };
    };
    "open-7.2.0" = {
      name = "open";
      packageName = "open";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/open/-/open-7.2.0.tgz";
        sha512 = "4HeyhxCvBTI5uBePsAdi55C5fmqnWZ2e2MlmvWi5KW5tdH5rxoiv/aMtbeVxKZc3eWkT1GymMnLG8XC4Rq4TDQ==";
      };
    };
  };
in
{
  pnpm = nodeEnv.buildNodePackage {
    name = "pnpm";
    packageName = "pnpm";
    version = "7.5.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/pnpm/-/pnpm-7.5.0.tgz";
      sha512 = "sb9wJNyx/d8l3Gze2jI1y8BGNbb/ga+JT3SrGNiH+C5KbtZ4wmgePBWGjaiGugcpT9+vQ5MO//+QlVWhMCpedQ==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Fast, disk space efficient package manager";
      homepage = "https://pnpm.io";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  speedscope = nodeEnv.buildNodePackage {
    name = "speedscope";
    packageName = "speedscope";
    version = "1.14.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/speedscope/-/speedscope-1.14.0.tgz";
      sha512 = "qz5eGE1OfkjshWyI4OLmMI0yzFg3fzlHKM96oAFFAaF8od4g6O5DdVi5IlX67q84irdK2aNB4gL7XMGao9mI7Q==";
    };
    dependencies = [
      sources."is-docker-2.2.1"
      sources."is-wsl-2.2.0"
      sources."open-7.2.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "English | [简体中文](./README-zh_CN.md) # 🔬speedscope";
      homepage = "https://github.com/jlfwong/speedscope#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
