# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "is-docker-2.2.1" = {
      name = "is-docker";
      packageName = "is-docker";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-docker/-/is-docker-2.2.1.tgz";
        sha512 = "F+i2BKsFrH66iaUFc0woD8sLy8getkwTwtOBjvs56Cx4CgJDeKQeqfz8wAYiSb8JOprWhHH5p77PbmYCvvUuXQ==";
      };
    };
    "is-wsl-2.2.0" = {
      name = "is-wsl";
      packageName = "is-wsl";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-wsl/-/is-wsl-2.2.0.tgz";
        sha512 = "fKzAra0rGJUUBwGBgNkHZuToZcn+TtXHpeCgmkMJMMYx1sQDYaCSyjJBSCa2nH1DGm7s3n1oBnohoVTBaN7Lww==";
      };
    };
    "open-7.2.0" = {
      name = "open";
      packageName = "open";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/open/-/open-7.2.0.tgz";
        sha512 = "4HeyhxCvBTI5uBePsAdi55C5fmqnWZ2e2MlmvWi5KW5tdH5rxoiv/aMtbeVxKZc3eWkT1GymMnLG8XC4Rq4TDQ==";
      };
    };
  };
in
{
  speedscope = nodeEnv.buildNodePackage {
    name = "speedscope";
    packageName = "speedscope";
    version = "1.13.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/speedscope/-/speedscope-1.13.0.tgz";
      sha512 = "PCrDVb3i/68U92DyiXBYP9NEVycnVczdNb+S5rlOiBdGMkX6qPlsir5U8rBtXx9kW8pYHkm4U+1nVtpx729Cfg==";
    };
    dependencies = [
      sources."is-docker-2.2.1"
      sources."is-wsl-2.2.0"
      sources."open-7.2.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A fast, interactive web-based viewer for performance profiles. An alternative viewer for [FlameGraphs][1]. Will happily display multi-megabyte profiles without crashing your browser.";
      homepage = "https://github.com/jlfwong/speedscope#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
