#!/usr/bin/env bash
# Bugs: It doesn't show the bg color of first line.

bg_color_code=('   ' '40m' '41m' '42m' '43m' '44m' '45m' '46m' '47m')
bg_color_name=('DFT' 'BLK' 'RED' 'GRN' 'YEL' 'BLU' 'MAG' 'CYN' 'WHT')
fg_color_code=('m' '1m' '30m' '1;30m' '31m' '1;31m' '32m' '1;32m' '33m' '1;33m' '34m' '1;34m' '35m' '1;35m' '36m' '1;36m' '37m' '1;37m')
fg_color_name=('DFT' 'DFT' 'BLK' 'BLK' 'RED' 'RED' 'GRN' 'GRN' 'YEL' 'YEL' 'BLU' 'BLU' 'MAG' 'MAG' 'CYN' 'CYN' 'WHT' 'WHT')

# TITLE
echo
echo -e "\033[${fg_color_code[5]}               ANSI Escape Code Referance                  \033[0m"
echo

# BACKGROUND COLOR NAME LINE
echo -en "       "
for ((i=0; i<9; i++)); do
    echo -en "  ${bg_color_name[i]} "
done
echo

# BACKGROUND COLOR CODE LINE
echo -en "       "
for ((i=0; i<9; i++)); do
    echo -en "  ${bg_color_code[i]} "
done
echo

# CONTENT
for ((i=0; i<18; i++)); do
    printf '%5s |' "${fg_color_code[i]}"
    for ((j=0; j<9; j++)); do
        echo -en "$EINS \033[${bg_color_code[j]}\033[${fg_color_code[i]} ${fg_color_name[i]} \033[0m"
    done
    echo
done
echo

# Other Useful Code
echo "Other Useful Code"
echo '        boldon    \033[1m      boldoff    \033[22m'
echo '        italicson \033[3m      italicsoff \033[23m'
echo '        ulon      \033[4m      uloff      \033[24m'
echo '        invon     \033[7m      invoff     \033[27m'
echo

# HELP
echo "Example:"
echo '         echo -e "\033[1;34m\033[46m EXAMPLE \033[0m"'
echo
