#!/usr/bin/env python3

# https://gist.github.com/taavi/5c9c9b3a24ee97840f68
# From https://wiki.python.org/moin/UdpCommunication modified for Statsd + debugging usage
import datetime
import socket

UDP_IP = "127.0.0.1"
UDP_PORT = 8125

sock = socket.socket(
    socket.AF_INET,     # Internet
    socket.SOCK_DGRAM)  # UDP
sock.bind((UDP_IP, UDP_PORT))

print(f'[INFO] StatsD server for debugging is listening on {UDP_IP}:{UDP_PORT}')

while True:
    data, addr = sock.recvfrom(1024)  # buffer size is 1024 bytes
    print(datetime.datetime.now(), data)
